##
# To enable RabbitMQ management console => docker exec [CONTAINER_NAME] rabbitmq-plugins enable rabbitmq_management
##

version: '3.3'
services:
  # redis:
  #     image: redis:alpine
  #     container_name: redis
  #     expose:
  #         - 6379
  #     ports:
  #         - 6379:6379
  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  # postgres:
  #     image: postgres:11-alpine
  #     container_name: postgres
  #     environment:
  #         POSTGRES_USER: amigo_admin
  #         POSTGRES_PASSWORD: amigo_pass
  #         POSTGRES_DB: amigo_db
  #     expose:
  #         - 5432
  #     ports:
  #         - 5432:5432
  #     volumes:
  #         - ./src/db/config/init.sql:/docker-entrypoint-initdb.d/init.sql
  #         - ./postgres-data:/var/lib/postgresql/data
# volumes:
#     postgres-data: